export const GET_MOVIE_START = "GET_MOVIE_START";
export type GET_MOVIE_START = typeof GET_MOVIE_START;

export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export type GET_MOVIE_SUCCESS = typeof GET_MOVIE_SUCCESS;

export const GET_MOVIE_ERROR = "GET_MOVIE_ERROR";
export type GET_MOVIE_ERROR = typeof GET_MOVIE_ERROR;
