export const GET_MOVIES_START = "GET_MOVIES_START";
export type GET_MOVIES_START = typeof GET_MOVIES_START;

export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export type GET_MOVIES_SUCCESS = typeof GET_MOVIES_SUCCESS;

export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";
export type GET_MOVIES_ERROR = typeof GET_MOVIES_ERROR;

export const SEARCH_MOVIES_START = "SEARCH_MOVIES_START";
export type SEARCH_MOVIES_START = typeof SEARCH_MOVIES_START;

export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export type SEARCH_MOVIES_SUCCESS = typeof SEARCH_MOVIES_SUCCESS;

export const SEARCH_MOVIES_ERROR = "SEARCH_MOVIES_ERROR";
export type SEARCH_MOVIES_ERROR = typeof SEARCH_MOVIES_ERROR;
