export const GET_RECOMMENDATIONS_START = "GET_RECOMMENDATIONS_START";
export type GET_RECOMMENDATIONS_START = typeof GET_RECOMMENDATIONS_START;

export const GET_RECOMMENDATIONS_SUCCESS = "GET_RECOMMENDATIONS_SUCCESS";
export type GET_RECOMMENDATIONS_SUCCESS = typeof GET_RECOMMENDATIONS_SUCCESS;

export const GET_RECOMMENDATIONS_ERROR = "GET_RECOMMENDATIONS_ERROR";
export type GET_RECOMMENDATIONS_ERROR = typeof GET_RECOMMENDATIONS_ERROR;